version: "3.8"

services:
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "despensa_db"
    ports:
      - 5432:5432
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d
