server:
  servlet:
    context-path: /despensaapi
    encoding:
      force: true
      enabled: true
      charset: utf-8
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/despensa_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 'postgres'


  jpa:
    show-sql: true
    generate-ddl: true






